### ISSUE TITLE
Initiate the calendar with pre-selected date

### ISSUE THREAD

**Issue by GovindaAgarwal** [accdc/accdc#5]
Hi,

Thanks for all the support thus far. 

We have used your AccDc datePicker and have a functionality where user can click on the modify search link and comes back with pre-selected values e.g. couple of values and date. If the date is future date then the date picker when opened while coming back using modify search link, still shows the current date in focus in the date picker. 

For example if I have selected 2/17/2016 in the initial search from the date picker and I click on the modify search, then I come back and open the date picker again. It shows today's date in focus even if tomorrow's date e.g. 2/17/2016 is selected. 

Appreciate any assistance with this.

**Comment by accdc** [comment]
Hi, I believe this should do the trick.

/*!
[setup.js.txt](https://github.com/accdc/accdc/files/781917/setup.js.txt)
Instructions
1. View the "ajax" function below to see how custom date ranges can be programmatically configured.
2. Take note of the calendar instance ID passed in the first parameter for the $A.setCalendar() function.
3. View the comments after the JavaScript function to see how HTML data-X attributes on the triggering element can be used to dynamically configure which date the calendar opens on.
*/

	// Syntax : setCalendar( ID , TriggeringElement , TargetEditField , EnableComments , clickHandler , config )

	$A.setCalendar('UniqueCalendarId', document.getElementById('dateIcon'), document.getElementById('date'), false,
		function(ev, dc, targ){
		// targ is the Input field with id="date"
		// Save the desired date string

		// mm/dd/yyyy format
		targ.value = ('0' + (dc.range.current.month + 1)).slice(-2) + '/' + ('0' + dc.range.current.mDay).slice(-2) + '/'
			+ dc.range.current.year;

		// Then close the date picker
		dc.close();
	},
					{
					// Set CSS positioning calculation for the calendar
					autoPosition: 3,
					// Customize with positive or negative offsets
					offsetTop: 0,
					offsetLeft: 5,

					// Run script before the calendar is rendered, every time
					ajax: function(dc, save){
						var date = new Date();

// Set this date object for whatever you want the calendar to open as the focused day/month/year

// You can optionally pull data-string attributes from the triggering element or the text input field to configure this too

// E.G Use three attributes on the Calendar triggering element to configure this functionality programmatically
// data-day, data-month, and data-year

						var day = parseInt($A.getAttr(dc.triggerObj, 'data-day')),
							month = parseInt($A.getAttr(dc.triggerObj, 'data-month')),
							year = parseInt($A.getAttr(dc.triggerObj, 'data-year'));

						if (!isNaN(day))
							date.setDate(day);

						if (!isNaN(month))
							date.setMonth(month);

						if (!isNaN(year))
							date.setFullYear(year);

						// Now configure a 'current' object that uses the date syntax within the datepicker JS instance
						// This will be used to merge into the datepicker before it opens
						var current =
										{
										day: date.getDate(),
										month: date.getMonth(),
										year: date.getFullYear(),
										weekDay: date.getDay()
										};

						// Now adjust the default date that the date picker first opens with using the previously set date object
						if (!dc.firstResetDate){
// Store a variable in the dc object to ensure this only runs when the date picker first opens, and not every time such as when switching between months or years
							dc.firstResetDate = true;
							// Now adjust the dates in the calendar to specify the current day to open the datepicker on
							// Uses the 'current' object variables to set the dates within the calendar before it opens
							dc.range.current.month = current.month;
							dc.range.current.mDay = current.day;
							dc.range.current.wDay = current.weekDay;
							dc.range.current.year = current.year;
						}

						// Now open the calendar
						dc.open();
					}
					});

/*!
So the above custom datepicker can be set by programmatically changing the data- attributes on the triggering element, such as the following syntax:

<a data-day="17" data-month="02" data-year="2017" 
role="button" aria-describedby="date" href="#" id="dateIcon" class="accCalendar datePicker" ...

Simply programmatically set new values for the data-day, data-month, and data-year attributes on the datepicker triggering element. This will cause the custom datepicker to open once at the specified date range.

To force the datepicker to recognize every time these attributes are changed, within the same script that updates these attributes, set the firstResetDate within the calendar instance to false as well, like so:

$A.reg['UniqueCalendarId'].firstResetDate = false;

The ID 'UniqueCalendarId' matches the first parameter passed in the $A.setCalendar() function, which sets an ID for the calendar instance so it can be configured like so from any script within your website.
*/
