### ISSUE TITLE
Keyboard Accessible Functionality availability for keyboard

### ISSUE THREAD

**Issue by GovindaAgarwal** [accdc/accdc#6]
Hi,

Next and Previous buttons seems to be not keyboard accessible. If a SR or Keyboard user press Shift+TAB then only focus moves to the Next and Previous button

It would be better if SR or Keyboard user can access the Next and Previous button using TAB key instead of Shift + TAB

**Comment by accdc** [comment]
Hi,
Actually a keyboard only user can press PageUp/PageDown or Alt+PageUp/PageDown to perform the same actions as the Next or Previous buttons, which is easier than trying to set focus to these buttons every time you want to move around the datepicker.

I agree that this is not immediately obvious to a sighted keyboard only user however, so the following technique can be used to add a custom tooltip when the calendar is rendered to clue the sighted user in that such commands are available to them.

Within your page stylesheet, add a pseudo element class that binds a CSS pseudo element to the calendar, like so:

div.calendar[role="dialog"]:after {
display: table;
height: auto; width: auto;
position: absolute; padding: 1px 0;
z-index: 2;
margin-top: 5px;
margin-left: -100px;
background-color: black;
color: orange;
font-size: .9rem; font-weight: 900;
content: ' Press PageUp/PageDown, Home/End, or the arrow keys to navigate. ';
}

You can use the margin-top, margin-left, and z-index properties to position the tooltip relative to any instance of the datepicker when rendered, which may be of help in providing additional help information for sighted keyboard only users.

**Comment by GovindaAgarwal** [comment]
Hi @accdc 

Thanks for your support. Sorry I could not find the way to re-open this ticket and hence commenting on the same ticket. 

Tooltip is a good option. However there is another observation which I wanted to share with you to provide some ideas. 

When I tab to calendar there are two elements that I can focus, one is the navigation arrow buttons and other is the days in the calendar itself. 

First time when I come to calendar the focus is on the calendar current day of the browser user is on and I can click to select the different date by tabbing. 

However when I shift tab, it moves in the way e.g. it goes to the right navigation arrow (for navigating months and years) and then to left navigation arrow and then out to the element from where it came to calendar. 

Is it possible to implement the same navigation behavior as we do when we shift tab. If yes then it would be great and satisfy our accessibility requirement. 

Expected behavior:
1. When I come to calendar the left button should be selectable and focus / highlight should be on the browser current date (the second part is already happening so nothing needs to be done for it)
2. When I tab again the right button should be selectable and focus / highlight should still be on the browser current date  (the second part is already happening so nothing needs to be done for it)
3. When I tab again then the days in the calendar should be selectable and I can continue tabbing to navigate to new days

Note - the above 3 steps is the current behavior when the keyboard user does shift + tab to navigate in the reverse direction.

**Comment by accdc** [comment]
Hi, I'm having trouble understanding what is being asked. So if you open the datepicker and focus is set on the current date as expected, what is supposed to happen when you press Tab at that point?

**Comment by GovindaAgarwal** [comment]
Hello @accdc 

Thanks for your response. 

The focus is set on the current date as expected, however when I tab, it should focus on the left navigation arrow and when I hit enter it should go to previous month. 

When I navigate using shift Tab to traverse in reverse direction, it actually goes from date to right navigation arrow and then left and then outside calendar. That's the same navigation pattern I am expecting should happen when I enter inside calendar.

**Comment by accdc** [comment]
Hi,
I've updated all of the calendar module JS files in the archive to support circular tabbing forward and backward as though the datepicker is a modal dialog from a keyboard perspective.

E.G
http://whatsock.com/tsg/Coding%20Arena/ARIA%20Date%20Pickers/ARIA%20Date%20Picker%20(with%20Disabled%20Date%20Ranges)/demo.htm


Regarding the order of which buttons get focus, this is actually following the standard tab order in the browser in the order they appear in the DOM, so the first two buttons that get focus are "Previous Year" and "Next Year", followed by the next two buttons "Previous Month and "Next Month", then focus is set to the focused date in the calendar.

This order seems logical to me because I either want to move by year or month one way or another. Is this an issue from your perspective?

**Comment by GovindaAgarwal** [comment]
@accdc 

Thanks for the updates. 

I am checking with new updates and get back to you.

**Comment by accdc** [comment]
As of this morning, you can also use the arrow keys in the Next/Prev Year and Month buttons as you like as well as the Tab and Shift+Tab keys for better navigation.

Also there is a new helpText property that can be set in the config setup.js file that will announce this content to screen reader users when the calendar opens, and this also adds a data-helptext attribute to the top level div element so you can add a CSS class in your stylesheet to display this for sighted keyboard only users as desired, which will reference the attribute value in the date picker when using content: attr(data-helptext) within the pseudo element CSS statement.

**Comment by GovindaAgarwal** [comment]
@accdc 

Thanks a lot. 

testing right now.

**Comment by GovindaAgarwal** [comment]
@accdc 

I tested the changes you made and it seems to be as I was expecting...thanks for your support

http://whatsock.com/tsg/Coding%20Arena/ARIA%20Date%20Pickers/ARIA%20Date%20Picker%20(with%20Disabled%20Date%20Ranges)/demo.htm
