### ISSUE TITLE
Date Picker - Accessible Keyboard - Navigating from first or last dates of the week

### ISSUE THREAD

**Issue by GovindaAgarwal** [accdc/accdc#8]
@accdc 

User is unable to navigate to next date using the right and left arrow keys when the user is in the last or first date of the week in the date picker. 

http://whatsock.com/tsg/Coding%20Arena/ARIA%20Date%20Pickers/ARIA%20Date%20Picker%20(with%20Disabled%20Date%20Ranges)/demo.htm

**Scenario 1:**
Steps to Replicate: Open the page and open calendar control. Now navigate the last date in week (Saturday dates) using RIGHT arrow key. 
Current behavior: User is not able to navigate to the next date using RIGHT arrow key. 
Expected behavior: User should be able to navigate to next date using RIGHT arrow keys.

**Scenario 2:**
Steps to Replicate: Open the page and open calendar control. Now navigate the first date in week (Sunday dates) using LEFT arrow key. 
Current behavior: User is not able to navigate to the previous date using LEFT arrow key. 
Expected behavior: User should be able to navigate to previous date using LEFT arrow keys.

**Comment by accdc** [comment]
Hi, this is now fixed. Thanks.

**Comment by GovindaAgarwal** [comment]
@accdc 

This is working now as expected. 

Appreciate your quick help with this.
