### ISSUE TITLE
Date Picker - Navigable (2.4.7.aa) Focus Visible

### ISSUE THREAD

**Issue by GovindaAgarwal** [accdc/accdc#9]
Hi @accdc 

Steps to Replicate: Navigate to Calendar Next button and press TAB key.

Current behavior: Focus is not visible on Date.

Expected behavior: Focus should be highly visible on Date. Use 3px blue border for visible focus caret line.

**Comment by accdc** [comment]
Thanks, I added a blue outline for all focusable elements within all calendars.
